MyMVC/Controllers/MyStoreController.cs
using Microsoft.AspNetCore.Mvc;
using MyMVC.Models;
using System.Data.SqlClient;

namespace MyMVC.Controllers
{
    public class MyStoreController : Controller
    {
        public IActionResult Index()
        {
            List< MyStore >List = new List< MyStore >();
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("select * from MyStore",con);
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                int id = Convert.ToInt32(reader["id"]);
                string Name= Convert.ToString(reader["Name"]);
                string Email = Convert.ToString(reader["Email"]);
                int Phone = Convert.ToInt32(reader["Phone"]);
                string Address= Convert.ToString(reader["Address"]);

                List.Add(new MyStore()
                {
                    Id = id,
                    Name=Name,
                    Email=Email,
                    Phone=Phone,
                    Address=Address
                });


            }
            con.Dispose();

            return View(List);
        } 
    }
}

MyMVC/Controllers/SoapStorController.cs
using Microsoft.AspNetCore.Mvc;
using MyMVC.Models;
using System.Data;
using System.Data.SqlClient;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography.X509Certificates;

namespace MyMVC.Controllers
{
    public class SoapStorController : Controller
    {
        public IActionResult Index()
        {
            List<SoapStor> list = new List<SoapStor>();
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("Select * From SoapStor", con);
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                int id = Convert.ToInt32(reader["ID"]);
                string Name = Convert.ToString(reader["SoapName"]);
                int Quntity = Convert.ToInt32(reader["Quntity"]);
                int Price = Convert.ToInt32(reader["Price"]);

                list.Add(new SoapStor
                {
                    Id = id,
                    SoapName = Name,
                    Quntity = Quntity, 
                    Price = Price
                });
            }

            return View(list);
        }


        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(SoapStor soapStor)
        {
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("insert into SoapStor values ('" + soapStor.SoapName + "','" + soapStor.Quntity + "','" + soapStor.Price + "')", con);
            command.ExecuteReader();
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult Edit(int Id)
        {
            SoapStor stor = new SoapStor();
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("SELECT * FROM SoapStor WHERE Id = " + Id + "", con);
            SqlDataReader reader = command.ExecuteReader();

            if (reader.Read())
            {
                stor.Id = Convert.ToInt32(reader["ID"]);
                stor.SoapName = Convert.ToString(reader["SoapName"]);
                stor.Quntity = Convert.ToInt32(reader["Quntity"]);
                stor.Price = Convert.ToInt32(reader["Price"]);
            }
            con.Close();
            return View(stor);
        }
             
            
        
        [HttpPost]
        public IActionResult Edit(SoapStor ess)
        {
            string connectionString = "Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True";
            var con = new SqlConnection(connectionString);
            con.Open();
            string query = "update SoapStor set SoapName = '" + ess.@SoapName + "', Quntity = '" + ess.@Quntity + "', Price = '" + ess.@Price + "' where Id ='" + ess.Id + "'";
            var command = new SqlCommand(query, con);
            command.ExecuteReader();
            con.Close(); 
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("delete SoapStor where Id=" + Id + "", con);
             command.ExecuteReader();
          
            return RedirectToAction("Index");


        }
    }
    }

MyMVC/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using MyMVC.Models;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Net;

namespace MyMVC.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            List<Student> students = new List<Student>();
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb;  Integrated Security=True");
            con.Open();
            var command = new SqlCommand("Select * From Student", con);
            SqlDataReader reader = command.ExecuteReader();

            while (reader.Read())
            {
                int Id = Convert.ToInt32(reader["Id"]);
                string Name = Convert.ToString(reader["Name"]);
                int Age = Convert.ToInt32(reader["Age"]);
                string FatherName = Convert.ToString(reader["FatherName"]);
                string MotherName = Convert.ToString(reader["MotherName"]);
                string Address = Convert.ToString(reader["Address"]);
                students.Add(new Student
                {
                    Id = Id,
                    Name = Name,
                    Age = Age,
                    FatherName = FatherName,
                    MotherName = MotherName,
                    Address = Address,
                });
            }
            con.Dispose();
            return View(students);
        }

        public IActionResult Insert()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Insert(Student student)
        {
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("insert into Student values ('" + student.Name + "','" + student.Age + "'" +
                ",'" + student.FatherName + "','" + student.MotherName + "','" + student.Address + "') ", con);
            command.ExecuteNonQuery();
            con.Dispose();

            return RedirectToAction(nameof(Index));

        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            Student student = new Student();
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("select * from Student where id=" + id + "", con);
            SqlDataReader reader = command.ExecuteReader();
            if (reader.Read())
            {
                student.Id = Convert.ToInt32(reader["ID"]);
                student.Name = Convert.ToString(reader["Name"]);
                student.Age = Convert.ToInt32(reader["Age"]);
                student.FatherName = Convert.ToString(reader["FatherName"]);
                student.MotherName = Convert.ToString(reader["MotherName"]);
                student.Address = Convert.ToString(reader["Address"]);
            }


            con.Dispose();

            return View(student);
        }

        [HttpPost]

        public IActionResult Update(Student ssp)
        {
            string ConnectionString = "Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True";
            var con = new SqlConnection(ConnectionString);
            con.Open();

            // string query = "update Student set Name ='" + ssp.@Name + "','" + ssp.@Age + "','" + ssp.@FatherName + "','" + ssp.@MotherName + "','" + ssp.@Address + "'";

            string query = "update Student set Name= '" + ssp.@Name + "',Age='" + ssp.@Age + "'" + ",FatherName='" + ssp.@FatherName + "',MotherName='" + ssp.@MotherName + "',Address='" + ssp.@Address + "' where Id ='"+ ssp.Id +"' ";
            var command = new SqlCommand(query,con);
            command.ExecuteReader();
            con.Dispose();


            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("Delete Student where id="+id+"",con);
            command.ExecuteReader();
            con.Dispose();
            return RedirectToAction("Index");
        }
    }
}

MyMVC/Controllers/TeacharController.cs
using Microsoft.AspNetCore.Mvc;
using MyMVC.Models;
using System.Data.SqlClient;
using System.Xml.Linq;

namespace MyMVC.Controllers
{
    public class TeacharController : Controller
    {
        public IActionResult Index()
        {
            List<Teachar> Rk = new List<Teachar>();

            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("select * from Teachar", con);
            SqlDataReader reader = command.ExecuteReader();

            while (reader.Read())
            {
                int Id = Convert.ToInt32(reader["ID"]);
                string Name = Convert.ToString(reader["Name"]);
                int Age = Convert.ToInt32(reader["Age"]);
                string Gender = Convert.ToString(reader["Gender"]);
                int AadharNo = Convert.ToInt32(reader["AadharNo"]);
                int phoneNo = Convert.ToInt32(reader["phoneNo"]);
                decimal Selery = Convert.ToDecimal(reader["Selery"]);
                string Address = Convert.ToString(reader["Address"]);

                Rk.Add(new Teachar()
                {
                    Id = Id,
                    Name = Name,
                    Age = Age,
                    Gender = Gender,
                    AadharNo = AadharNo,
                    phoneNo = phoneNo,
                    Selery = Selery,
                    Address = Address,

                });   
            }
            con.Dispose();
            return View(Rk);
        }

        public IActionResult Insert()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Insert(Teachar teachar)
        {
            var con = new SqlConnection("Data Source=ARVIND; Initial Catalog=SatishMVCdb; Integrated Security=True");
            con.Open();
            var command = new SqlCommand("insert into Teachar values ('" + teachar.Name + "','" + teachar.Age + "'" +
                ",'" + teachar.Gender + "','" + teachar.AadharNo + "','" + teachar.phoneNo + "','" + teachar.Selery + "','" + teachar.Address + "') ", con);
            command.ExecuteNonQuery();
            con.Dispose();

            return RedirectToAction(nameof(Index));
        }






    }
}

MyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachar" asp-action="Index">Teachar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SoapStor" asp-action="Index">SoapStor</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyStore" asp-action="Index">MyStore</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>